#! /bin/sh

sxhkd &
compton &
dunst &
xscreensaver &
polybar example -r &
redshift -P -O 3500 &

bash $HOME/.scripts/bspwmstartup
source ~/.profile

bspc monitor HDMI1 -d a s d f g h j k
bspc monitor eDP1 -d  1 2 3 vim 5 6 7 gimp music 零 零 零 零

bspc config border_width         0
bspc config focused_border_color "#ababab"
bspc config window_gap           4
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
