#! /bin/sh

sxhkd &
compton &
dunst &
xscreensaver &
polybar example -r &
redshift -P -O 3500 &

bash $HOME/.scripts/bspwmstartup
source ~/.profile

bspc monitor HDMI1 -d I II III TMUX VIM VII VIII W
bspc monitor eDP1 -d  I II III TMUX VIM VII VIII W IV VX

bspc config border_width         0
bspc config focus_follows_pointer true
bspc config focused_border_color "#ababab"
bspc config window_gap          4
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
